# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

# Orchestrate or schedule a set of jobs


defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  
commands:
  checkout_command:
    steps:
      - run: checkout

jobs:
    build:
      <<: *defaults

      steps:
        - checkout_command
        - run: npm i
        - save_cache:
          - key: "npm-package"
          - paths:
            - /src/node/modules
        - run: npm run lint

    test:
      <<: *defaults

      steps:
        - checkout_command
        - restore_cache:
            keys: "npm-package"
        - run: npm i
        - run: npm run test

    analyze:
      <<: *defaults

      steps:
        - checkout_command
        - restore_cache:
            keys: "npm-package"
        - run: npm audit
        - run: 
            name: on error
            command: echo "This test failed"
            when: on_fail
            
workflows:
  # Name the workflow "welcome"
  myWorkFlow:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
